#patreon: SolidInvoice
open_collective: SolidInvoice
github: SolidInvoice
tidelift: packagist/solidinvoice%2Fsolidinvoice
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EQLK2P3VBW2LC
